### ISSUE TITLE
안녕하세요 종권님. 코드에 관해 질문이 있어 이슈 남깁니다.

### ISSUE THREAD

**Issue by insub4067** [JK0369/WeatherApp#1]
안녕하세요. 종권님.
저는 주니어 iOS 개발자 김인섭이라고 합니다.
종권님 블로그와 깃헙보며 많이 배우고 있습니다. 항상 감사합니다.
종권님 코드보며 공부하다 질문이 있어서 이슈 남깁니다.
시간 괜찮으시다면 답변해주시면 감사하겠습니다.

```swift
class WeatherViewController: UIViewController, WeatherPresentable {
  private let disposeBag = DisposeBag()
  private let stateSubject = PublishSubject<WeatherState>()
  let viewModel: WeatherViewModelable
  var stateObservable: Observable<WeatherState> {
      stateSubject
  }

  private func bind() {
    stateSubject
        .observe(on: MainScheduler.instance)
        .bind(with: self) { ss, state in
            ss.handleOutput(state)
        }
        .disposed(by: disposeBag)
    
    viewModel.output
        .observe(on: MainScheduler.instance)
        .bind(to: stateSubject)
        .disposed(by: disposeBag)
  }
}
```

위 코드는 ViewModel 의 코드 일부인데요. 
아래와 같이 viewModel.output 을 구독하여 바로 handleOutput 으로 넘길 수 있을 것 같은데 위와 같이 
viewModel.output -> stateSubject -> handleOutput 으로 데이터의 흐름이 구성된 이유가 궁금합니다. 

```swift
    private func bind() {

        viewModel.output
            .observe(on: MainScheduler.instance)
            .bind(onNext: { [weak self] state in
                self?.handleOutput(state)
            })
            .disposed(by: disposeBag)
    }
```

**Comment by JK0369** [comment]
안녕하세요, 인섭님. @insub4067 
요즘 일이 바쁘다보니 지금 확인했네요.

1. stateSubject를 만든 이유
말씀해주신대로 공유해주신 코드 부분만 보면 stateSubject가 필요 없겠지만, `WeatherPresentable` 프로토콜을 준수하기 위해서 subject를 따로 만들었습니다.
`WeatherPresentable` 프로토콜을 보시면 `stateObservable` 프로퍼티가 있는것을 확인할 수 있어요.
현재 코드에서는 WeatherPresentable를 다른곳에서는 사용하고 있어서 의미가 크게 느껴지지 않겠지만, ViewController를 여러곳에서 사용할 
때 protocol를 통해 준수하게하는 것이 중요합니다. (DIP 원칙 및 테스트 가능한 코드를 위함) 
* DIP 원칙 및 테스트 가능한 코드에 관한 개념은 이 포스팅 글 읽어보시면 도움이 될 거에요: https://ios-development.tistory.com/1377

정리하면 WhaterViewController를 사용하는 쪽에서는 WhaterViewController 자체를 참조하게 하지 않고 WeatherPresentable을 참조하게끔 하기 위해 WeatherPresentable을 따로 만들었으며 WhaterViewController가 준수하게끔 하였고, 여기서 `stateObservable` 프로토콜이 필요하여 stateSubject 프로퍼티를 통해 데이터 흐름을 유도한것이에요.

2. stateSubject만을 통해 handleOutput 바인딩하는 이유
논리 흐름상 가장 자연스럽기 때문입니다.
stateSubject, stateObservable, viewModel.ouput 세 가지 모두 바인딩하여 handleOutput에 넘겨줄 수 있지만, 
코드 성격상 viewModel로 부터의 output 이벤트는 모두 stateSubject에 최초로 바인딩 되는데, 
이 이벤트는 각자 필요한 구독자에게 (stateObservable, viewModel.output)에게 다시 넘겨주는 논리 흐름이 가장 자연스럽다고 생각한 이유입니다.

궁금한 점 있으면 말씀 또 부탁드려요.
감사합니다.
